apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend.yaml
- frontend.yaml
images:
- name: khoanncontainerregistry.azurecr.io/backend
  newTag: "724"
- name: khoanncontainerregistry.azurecr.io/frontend
  newTag: "723"
