---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: mongo-sc
# provisioner: kubernetes.io/aws-ebs
# parameters:
#   type: gp2
# volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-sc
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  location: eastus
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  selector:
    name: mongo
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  MONGODB_INITDB_ROOT_USERNAME: "user"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
data:
  MONGODB_INITDB_ROOT_PASSWORD: cGFzc3dvcmQK
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      name: mongo
  serviceName: "mongo"
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: mongo
        image: mongo
        ports:
          - containerPort: 27017
        envFrom:
         - configMapRef:             
               name: mongo-config
         - secretRef:
             name: mongo-secrets
        volumeMounts:
            - name: data-volume
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        storageClassName: mongo-sc
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: data-volume
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: fast
#   resources:
#     requests:
#       storage: "1Gi"
